# Enable 256-color and true color (24-bit) support in tmux
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# ========== General ==========
set -g set-clipboard on
set -g mouse on
set -g status-interval 3 # (default: 15)
set -g detach-on-destroy off

# Set prefix key
unbind C-b
set -g prefix C-Space

# Refresh tmux config
unbind r
bind -N "Reload tmux config" r source-file ~/.config/tmux/tmux.conf

# Splits
unbind %
bind -N "Split window horizontally" V split-window -h -c "#{pane_current_path}"
unbind \"
bind -N "Split window vertically" v split-window -v -c "#{pane_current_path}"

# New window in the same path
bind c new-window -c "#{pane_current_path}"

bind -N "Maximize Pane" -r m resize-pane -Z

# Copy mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"
unbind -T copy-mode-vi MouseDragEnd1Pane

# Start window and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Instantly kill panes
bind -N "Kill pane" x kill-pane
unbind &
bind -N "Kill window" X kill-window

bind -n M-g display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"

# List of plugins
# TMUX plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Enable navigating between nvim and tmux
set -g @plugin 'christoomey/vim-tmux-navigator'

# Persists tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Automatically saves sessions every 15 minutes
set -g @plugin 'tmux-plugins/tmux-continuum'

# CPU and memory info
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Style
# bg="#3B4252"
bg="default"
default_fg="#D8DEE9" 
session_fg="#A3BE8C"
session_selection_fg="#3B4252"
session_selection_bg="#81A1C1"
active_window_fg="#88C0D0"
active_pane_border="#abb2bf"

set -g status-left-length 200   # default: 10
set -g status-right-length 200  # default: 10
set -g status-left "#[fg=${session_fg},bold,bg=${bg}] #S #[fg=${default_fg},nobold,bg=${bg}] "
set -g status-right " #{cpu -i 3}   #{mem} "
set -g status-justify centre
set -g status-position top
set -g status-style "bg=${bg}"
set -g window-status-format "#[fg=${default_fg},bg=default]  #I:#W"
set -g window-status-current-format "#[fg=${active_window_fg},bold,bg=default]  #[underscore]#I:#W"
set -g window-status-last-style "fg=${default_fg},bg=default"
set -g message-command-style "bg=default,fg=${default_fg}"
set -g message-style "bg=default,fg=${default_fg}"
set -g mode-style "bg=${session_selection_bg},fg=${session_selection_fg}"
set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style "fg=brightblack,bg=default"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm
